# Project information
site_name: "Lesson 1.1: Operating on data structures"
site_description: Proof of concept for lesson
site_author: University of Leeds
site_url: https://squidfunk.github.io/mkdocs-material/

Repository
repo_name: darloboy101/mkdoc_test001  
repo_url: https://github.com/darloboy101/mkdoc_test001

# Copyright
copyright: Copyright &copy; 2020 University of Leeds

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: teal
    accent: teal
  font:
    text: Roboto
    code: Roboto Mono
#  features:
#    - tabs
  icon:
    logo: material/teach
#    logo: fontawesome/brands/python
  
# Google Analytics
google_analytics:
  - UA-XXXXXXXX-X
  - auto

nav:
  # - "Lesson 1.1: Operating on data structures": index.md
  - Strings, list and indices: page001.md
  - Tuples and Lists: page002.md

  # - Displaying code: sample002.md


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML



# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

